[workspace]

members = [
    "rest",
    "client",
    "settings"
]

[workspace.dependencies]
taple_core = { git = "https://github.com/opencanarias/taple-core", package = "core", tag = "v0.1.2"}
commons = { git = "https://github.com/opencanarias/taple-core", tag = "v0.1.2" }

[profile.release]
lto = true
codegen-units = 1
debug = false
debug-assertions = false
panic = "abort"

[profile.test]
debug = true

[profile.dev]
debug = true

[profile.doc]
debug-assertions = false
