#!/bin/bash

TOOLS_IMAGE="opencanarias/taple-tools:0.3"
TOOL="taple-sign"

ARGS=()
for var in "$@"
do
    ARGS+=("$var")
done

docker run --rm --name docker-taple-sign ${TOOLS_IMAGE} ${TOOL} "${ARGS[@]}"