#!/bin/bash

TOOLS_IMAGE="opencanarias/taple-tools:0.2.0"
TOOL="taple-keygen"

ARGS=()
for var in "$@"
do
    ARGS+=("$var")
done

docker run --rm --name docker-taple-sign ${TOOLS_IMAGE} ${TOOL} "${ARGS[@]}"