[package]
name = "settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.1.3", features = ["string"] }
toml = "0.6.0"
thiserror = "1.0"
lazy_static = "1.4.0"
regex = "1.7.1"
