[package]
name = "settings"
version = "0.2.0"
edition = "2021"
description = "Dynamic configuration builder based on CLAP"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
linked_hash_set = { workspace = true }